### ISSUE TITLE
Compatibility with Next new thread optimization

### ISSUE THREAD

**Issue by ruimonteiro93** [moxystudio/next-compile-node-modules#11]
Next's latest versions have MultiThread optimization implemented:   [https://github.com/vercel/next.js/blob/435bf657847329c753b6c0633f6580a62dddb8ba/packages/next/build/webpack-config.ts#L753](url)

This package should support these updates. In order to do this, the cache-loader config should be changed.

**Comment by satazor** [comment]
It seems `babelMultiThread` was removed, closing.
